import type { Metadata } from "next";
import { Barlow_Semi_Condensed, Nunito } from "next/font/google";
import "./globals.css";
import Navbar from "../components/navbar"; // 👈 importa tu navbar
import SocialMedia from "@/components/socialMedia";

const barlow = Barlow_Semi_Condensed({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
  variable: "--font-barlow",
});

const nunito = Nunito({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
  variable: "--font-nunito",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${nunito.variable} ${barlow.variable} antialiased`}>
        <Navbar /> 
        <main>{children}</main> {/* deja espacio para el navbar */}
        <SocialMedia/>
      </body>
    </html>
  );
}
